### ISSUE TITLE
Example server sticks if requested except /helloworld.Greeter/SayHello

### ISSUE THREAD

**Issue by KOBA789** [tower-rs/tower-h2#1]
It returns `RspBody::empty()` when the requested url is not matched to `ROOT`.
https://github.com/tower-rs/tower-h2/blob/9350015/examples/server.rs#L71

And it constructs a `RspBody` containing `None`.
https://github.com/tower-rs/tower-h2/blob/9350015/examples/server.rs#L30

So `RspBody::is_end_stream` always returns `false`.
https://github.com/tower-rs/tower-h2/blob/9350015/examples/server.rs#L39

Is this intended?

**Comment by carllerche** [comment]
Probably not :) I think the examples probably need to be rewritten at this point. They have stagnated a bit.

**Comment by KOBA789** [comment]
I see! Thank you for your answer.
