### ISSUE TITLE
Errors don't implement Error (nor Fail)

### ISSUE THREAD

**Issue by vorner** [tower-rs/tower-h2#15]
I guess this is simply due to early development state, but still.

Working with the returned errors is somewhat uncomfortable, as they don't implement `std::error::Error`, nor anything similar (like `failure::Fail`). Whenever I try to integrate them into something designed to handle errors, it refuses to compile.

**Comment by hawkw** [comment]
@vorner I've opened a PR #16 to implement `Error` for `tower-h2`'s error types. 

I haven't added support for `failure` at this point to avoid a dependency on `failure`, though eventually that could be behind a Cargo feature so users of `failure` could opt into support for that library.

**Comment by hawkw** [comment]
> I don't think the feature gate makes sense, since `Fail` is implemented for all `Error`s by failure crate itself.

Ah, okay, I've never used `failure` & wasn't aware of that. In that case, this should probably be sufficient, then?
